### PR TITLE
add generic get put post and delete methods

### PR DESCRIPTION
**Pull request by ghost**
this will allow for implementation of all api calls in docs
http://pve.proxmox.com/pve2-api-doc/

### CODE REVIEW

**Comment by nledez** [comment]
Hello @bhedana,

Thanks for your PR, but tests are missing:
As you can see in https://travis-ci.org/nledez/proxmox/jobs/91181265:
Coverage is at 95.74%.

Before it was 100%. If I found some time to add tests, I can merge your PR. But if you can add yourself, it can be faster :p

**Comment by bhedana** [comment]
tests added

**Comment by nledez** [comment]
Thanks for your job. Next time, it could be better to have separate commit between test add & code lint.

**Comment by ghost** [comment]
certainly

**Comment by nledez** [comment]
Could you add doc such as https://github.com/nledez/proxmox/blob/master/lib/proxmox.rb#L53-L68

And more explicit test description:
https://github.com/nledez/proxmox/blob/master/spec/lib/proxmox_spec.rb#L62

Thanks again.

**Comment by ghost** [comment]
i'm on that..

if you'd revert the merge of this pull request i can also separate the spec commit from the lint while i'm at it..

**Pull request merged**
